use_frameworks!

target 'PNTwitterCover_Example' do
  pod 'PNTwitterCover', :path => '../'

  target 'PNTwitterCover_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
